### ISSUE TITLE
Error.js在生成错误时未处理完全导致DEBUG信息不全

### ISSUE THREAD

**Issue by Lautitia** [PingPlusPlus/pingpp-nodejs#1]
微信支付渠道未正确开通的时候，PingppResource.js::_responseHandler中获取了服务器的正确错误信息，错误信息如下
{ error: 
   { type: 'channel_error',
     message: 'The request for channel was unsuccessful. Error message from channel wx_new: 支付权限检查失败',
     code: 'channel_request_error' } }
但在Error.js::generate中，switch语句并未处理'channel_error'这个type，导致日志throw了一个Unknow Error，给DEBUG带来麻烦

**Comment by samurai00** [comment]
已经在 2.0.6 版本修复
