### ISSUE TITLE
Feature: 在初始化时，增加app_id的配置

### ISSUE THREAD

**Issue by yorkie** [PingPlusPlus/pingpp-nodejs#2]
Hey

在你们API中发现一个有点奇怪的地方，每次创建charge时，都需要传递`app.id`，不过这个不是应该在初始化`pingpp`的时候就应该进行设置吗？

如果是考虑到需要多个app的情况，在配置的时候覆盖掉就好

谢谢

**Comment by samurai00** [comment]
因为我们的 API 是将 app_id 作为其中一个参数的，所以不能与其它参数区别对待。你可以将 app_id 写到你的配置。
