### ISSUE TITLE
IPv6支持

### ISSUE THREAD

**Issue by rankjie** [PingPlusPlus/pingpp-nodejs#7]
似乎 charges.create 的 client_ip 不支持 IPv6，不知道是Pingxx服务器那边本身就不支持还是SDK这边没有考虑过这问题？

**Comment by samurai00** [comment]
是的。这个不支持 ipv6。如果获取不到 ipv4，请自定义一个 ipv4 地址。
这个与 sdk 无关，API 决定是否支持。
