### ISSUE TITLE
验证webhooks签名的函数是哪个？

### ISSUE THREAD

**Issue by CyrusLiu158** [PingPlusPlus/pingpp-nodejs#8]
文档里看到下面的内容，但没找到验签方法：

验证签名

Ping++ 在管理平台中提供了 RSA 公钥，供验证签名，该公钥具体获取路径：点击管理平台右上角公司名称->开发信息-> Ping++ 公钥。验证签名需要以下几步：

从 header 取出签名字段并对其进行 base64 解码。
获取 Webhooks 请求的原始数据。
将获取到的 Webhooks 通知、 Ping++ 管理平台提供的 RSA 公钥、和 base64 解码后的签名三者一同放入 RSA 的签名函数中进行非对称的签名运算，来判断签名是否验证通过。 Ping++ 提供了验证签名的 Demo ，放在 SDK 的 example 里供参考，此处不再赘述。

**Comment by samurai00** [comment]
参考这个文件 https://github.com/PingPlusPlus/pingpp-nodejs/blob/master/example/webhooks_verify.js
